### ISSUE TITLE
Missing PCA plots and data imputation error

### ISSUE THREAD

**Issue by ghost** [antonvsdata/notame#2]
Hi, 

I'm Esther and I am using this package for non-targeted metabolomics. I came across Daniel's blog post on the use of this package at https://danielquiroz97.gitlab.io/post/notame/  and have encountered some issues that I would like to seek consult on. 

1) Missing PCA plots after doing drift correction at the preprocessing step.
The code line that gave this error is is corr_pca <- plot_pca(corrected, center = T) 

I also faced the same issue when I tried to do batch correction at this code line:
batch_pca <- plot_pca(corrected_batch, center = T, color = "Batch_ID", shape = "Class") 
For the batch correction, there was an error message mentioning "Data is not numeric" and contains NAs. It is also noted that the same error msg appears when I tried the example dataset given in the package "sample_data_whole" where I selected mode <- modes$HILIC_positive. However, the data did not contain any NAs. 

2) When I move on to preprocessing part 2 (https://danielquiroz97.gitlab.io/post/notameii/), running data imputation at line
imputed <- impute_rf(all_noQC, all_features = T) returns me an error "Error in xAttrib[[t.co]] : subscript out of bounds".

I was unable to continue with the analysis afterwards. 

Kindly advise. Please find the dataset & the script attached.

Thank you!

Regards,
Esther

[Notame R.zip](https://github.com/antonvsdata/notame/files/5828794/Notame.R.zip)

**Comment by antonvsdata** [comment]
Hi Esther,

Apologies, I had completely missed this issue! I tried running your code with the latest notame version and at least the line  
`corr_pca <- plot_pca(corrected, center = T)` runs just fine.

I think the rest of the problems are due to the fact that you performed batch correction, even though there only seems to be one batch of samples. Or at least the Batch_ID column is 1 for all the samples. It seems that the batch correction function from the `BatchCorrMetabolomics` package produces only NAs in this case, which is why all of the feature abundances after batch correction are NAs.

This probably won't be useful to you after such a long delay, but at least there is an explanation to the errors. I will close this issue.

Regards,
Anton
